### ISSUE TITLE
Incomplete global_planner input system

### ISSUE THREAD

**Issue by Kanomus** [Kanomus/OpenCVProject#1]
Currently the input system of global_planner takes inputs for start and end positions on a map with left and right clicks, and then gives no visual clue about those points, and starts the simulation after exiting with escape key.

We want this input system to be such that at least the selected start and end points are visible on the map before confirming with a key like enter, which starts the simulation with those chosen points, that too only if both selected points lie on a valid area (roads)

**Comment by Chimankarparag** [comment]
Soham added an input system on mouse clicks. However, the user can't see his selected places in real time. It can only be done after enter is pressed.

**Comment by Kanomus** [comment]
Input system is complete now, issue closed
